#!/bin/bash

# shellcheck disable=SC1091

GITEA_URL="https://github.com/go-gitea/gitea"

VERSION=${1:?version is error}
package_sha256=${2:?sha is error}

base_name="releases/download/v$VERSION/gitea-$VERSION-linux-amd64"
directory="/apps/gitea/bin"

echo "Downloading gitea package"
[ ! -d $directory ] && mkdir -pv $directory
curl -L -k --output $directory/gitea --silent --show-error --fail  "https://ghproxy.com/${GITEA_URL}/${base_name}"

if [ -n "$package_sha256" ]; then
    echo "Verifying package integrity"
    echo "$package_sha256  $directory/gitea" | sha256sum -c - || exit "$?"
fi

chmod +x /apps/gitea/bin/gitea
upx -9 /apps/gitea/bin/gitea
