#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global environment variables
. /etc/s6/s6-init/envs

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

#==================================#
# Prepare persistence directories. #
#==================================#
info "Prepare persistence directories."
for pdir in "${PHP_PERSISTENCE_LIST[@]}"
do
    # Ensure a directory exists and,is owned by the given user
    ensure_dir_exists "$pdir" "git"
done

#=====================#
#   Prepare Gitea     #
#=====================#
GITEA_APP_INI="/apps/gitea/etc/app.ini"
info "Render gitea config with envionment variables."
su-exec git /usr/bin/render-template ${GITEA_APP_INI}.tpl > $GITEA_APP_INI
owned_by "$GITEA_APP_INI" "git"

# Prepare database
su-exec git gitea migrate --config $GITEA_APP_INI

ISCREATED=$(su-exec git  gitea admin user list --admin --config ${GITEA_APP_INI} | wc -l)

if [ "$ISCREATED" != "2" ];then
    # Create admin user
    su-exec git gitea admin user create \
        --username "${DEFAULT_ADMIN_USERNAME}" \
        --password "${DEFAULT_ADMIN_PASSWORD}" \
        --email "${GITEA_ADMIN_EMAIL}" \
        --admin \
        --config ${GITEA_APP_INI} \
        && su-exec git gitea admin user list --config ${GITEA_APP_INI}
fi
