#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global environment variables
. /etc/s6/s6-init/envs

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

#==================================#
# Prepare persistence directories. #
#==================================#
info "Prepare persistence directories."
for pdir in "${PHP_PERSISTENCE_LIST[@]}"
do
    # Ensure a directory exists and,is owned by the given user
    ensure_dir_exists "$pdir" "git"
done

#=====================#
#   Prepare Gitea     #
#=====================#
export LOG_LEVEL="Info"
if [ -n "${DEBUG:+1}" ];then
  export LOG_LEVEL="debug"
fi

# Persistence SECRET_KEY and LFS_JWT_SECRET
SECRET_KEY_FILE="/data/.SECRET_KEY"
LFS_JWT_SECRET="/data/.LFS_JWT_SECRET"
 
if [ ! -f $SECRET_KEY_FILE ] || [ ! -s $SECRET_KEY_FILE ];then
  gitea generate secret SECRET_KEY > $SECRET_KEY_FILE
fi
  
if [ ! -f $LFS_JWT_SECRET ] || [ ! -s $LFS_JWT_SECRET ] ;then
  gitea generate secret LFS_JWT_SECRET > $LFS_JWT_SECRET
fi

GITEA_SECRET_KEY=$(cat $SECRET_KEY_FILE)
GITEA_LFS_JWT_SECRET=$(cat $LFS_JWT_SECRET)
export GITEA_SECRET_KEY
export GITEA_LFS_JWT_SECRET

# Render app.ini
GITEA_APP_INI="/apps/gitea/etc/app.ini"
info "Render gitea config with envionment variables."
su-exec git /usr/bin/render-template ${GITEA_APP_INI}.tpl > $GITEA_APP_INI
owned_by "$GITEA_APP_INI" "git"

# Prepare database
su-exec git gitea migrate --config $GITEA_APP_INI

# Deprecated 1.20.1  database mysql charset utf8 support, please use utf8mb4 and convert utf8 database to utf8mb4
ISCREATED=$(su-exec git  gitea admin user list --admin --config ${GITEA_APP_INI} | grep Deprecated | wc -l)

if [ "$ISCREATED" == "1" ];then
    # Create admin user
    su-exec git gitea admin user create \
        --username "${DEFAULT_ADMIN_USERNAME}" \
        --password "${DEFAULT_ADMIN_PASSWORD}" \
        --email "${GITEA_ADMIN_EMAIL}" \
        --admin \
        --config ${GITEA_APP_INI} \
        && su-exec git gitea admin user list --config ${GITEA_APP_INI}
fi
